### ISSUE TITLE
Broken on Netscape

### ISSUE THREAD

**Issue by carlosrojas** [martinvelez/martinvelez.github.com#2]
This website looks broken on my Netscape browser. Fix ASAP!

**Comment by martinvelez** [comment]
Have you tried turning it off and on again?

**Comment by martinvelez** [comment]
Except for the Projects section, the rest of the website looks fine.  

![Screen Shot 2021-01-11 at 11 18 30 AM](https://user-images.githubusercontent.com/397957/104227820-d2e5b480-53fe-11eb-89f9-b4125ff8219a.png)

Thus, I am closing this issue.  Thank you for reporting this.  I look forward to more reports.
